  
server:
  port: 8080
  servlet:
    context-path: 
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  ssl:
    enabled: true
    key-alias: springbootSecurity
    key-store: springbootSecurity.pkcs12
    key-store-password: 'whrhkdgus1'
    key-password: 'whrhkdgus1'
    trust-store: springbootSecurityTrust.pkcs12
    trust-store-password: 'whrhkdgus1' 
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update   #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 547183999372-k2mkcsmvv49h1oibsp6d0lqlipgtp0t7.apps.googleusercontent.com
            client-secret: qQTERzOEDW2k6aDWB9lJ-Tal
            scope:
            - email
            - profile
          facebook:
            client-id: 3020102224870744
            client-secret: cd4f87ecf52ab4ae7d131419c643bc30
            scope:
            - email
            - public_profile
          naver:
            client-id: HLsfr3EIlWlmqFi3pG_M
            client-secret: v2BrPISxtQ
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: https://localhost:8080/login/oauth2/code/naver  
            
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌